/* Motion, visual discovery, and browser-local preview accounts. */
logo=(light=false)=>`<a class="grove-logo grove-wordmark v4-logo ${light?'light':''}" href="#/landing" aria-label="The Grove homepage"><img src="assets/grove-symbol.svg" alt=""><span><small>the</small><b>grove</b></span></a>`;
imgs.cookies='https://images.unsplash.com/photo-1652284303404-4f46665cbb6f?auto=format&fit=crop&w=1000&q=85';
imgs.beauty='https://images.unsplash.com/photo-1728842920167-8122270260fe?auto=format&fit=crop&w=1000&q=85';
imgs.jewellery='https://images.unsplash.com/photo-1585832641917-c40a6d4cec77?auto=format&fit=crop&w=1000&q=85';
businesses.find(b=>b.id===4).image='cookies';
imgs.clay='https://images.unsplash.com/photo-1595351298020-038700609878?auto=format&fit=crop&w=1000&q=85';
imgs.fern='https://unsplash.com/photos/r0M9HrfJMBM/download?force=true&w=1000';
businesses.find(b=>b.id===5).image='clay';
businesses.find(b=>b.id===6).image='fern';
const motionScene=(extra='')=>`<div class="motion-scene ${extra}" role="img" aria-label="Grove waves and blinks in a neighbourhood of home businesses"></div>`;
const welcomeScene=()=>`<div class="welcome-world"><span class="welcome-orbit orbit-one">✦</span><span class="welcome-orbit orbit-two">♡</span><div class="welcome-ticket">YOUR NEXT CHAPTER<span>starts with a hello.</span></div><img class="welcome-mascot" src="assets/grove-mascot.png" alt="Grove bouncing and greeting you"><span class="welcome-floor"></span><span class="welcome-pill">A LITTLE CURIOUS. VERY YOU.</span></div>`;
const landingBeforeMotion=landing;
landing=function(){const t=document.createElement('template');t.innerHTML=landingBeforeMotion();const d=t.content;
d.querySelector('.landing').classList.add('v4-landing');
d.querySelector('.hero-ctas [data-entry="owner"]')?.remove();
d.querySelector('.hero-text>p').textContent='Singapore’s little businesses. Your next big favourite. Discover makers near you and get $1 off each next stop in your chain.';
d.querySelector('#hero-scene-image').outerHTML=motionScene('hero-motion');
d.querySelector('.scene-selector').outerHTML='<button class="motion-control" data-motion="pause" aria-pressed="false">Pause animation Ⅱ</button>';
d.querySelectorAll('.process-section,.why-section,.owner-section,.recommendation-note').forEach(x=>x.remove());
d.querySelector('.v3-about').innerHTML=`<div><span class="eyebrow">SMALL BUSINESSES. STRONGER CONNECTIONS.</span><h2>Local feels<br><em>more personal.</em></h2><p>Our mission: help Singapore’s home-grown talent get discovered, and give every little business room to grow.</p></div><div class="mission-art"><span class="mission-loop"></span><div class="mission-node node-a">♡<strong>Find your people</strong><small>Curious locals</small></div><div class="mission-node node-b">✦<strong>Share your passion</strong><small>Home-grown makers</small></div><span class="mission-label">A neighbourhood of possibility</span></div>`;
d.querySelector('.benefit-strip').remove();
const photos=[imgs.bread,imgs.beauty,imgs.pottery,imgs.jewellery];
d.querySelectorAll('.category-tile').forEach((el,i)=>{el.querySelector('.category-doodle').remove();el.insertAdjacentHTML('afterbegin',`<div class="category-photo"><img src="${photos[i]}" alt="${['Fresh artisan bread','Bottled skincare','Handcrafted ceramics','Gold jewellery'][i]}" loading="lazy"><span>${['Taste something good','Make time for yourself','Made with imagination','Wear a little personality'][i]}</span></div>`);el.querySelector('p').remove()});
d.querySelectorAll('.chain-business-symbol').forEach((el,i)=>el.innerHTML=`<img src="${[imgs.bread,imgs.pottery,imgs.jewellery][i]}" alt="" loading="lazy">`);
d.querySelector('.chain-explainer').textContent='First stop starts your chain. Each next different business: $1 off. Four stops = $3 saved.';
d.querySelector('.tools-showcase').id='owners';
d.querySelector('.tools-showcase>div:first-child').insertAdjacentHTML('beforeend',`<div class="studio-actions">${entryButton('Grow your business','owner','btn')}<button class="motion-control" data-motion="tools" aria-pressed="false">Pause showcase Ⅱ</button></div>`);
d.querySelector('#tool-preview').setAttribute('role','tabpanel');
d.querySelectorAll('.faq-section details').forEach((el,i)=>{if(i===1||i===5)el.remove()});
d.querySelector('.faq-grove').outerHTML=`<div class="faq-host"><div class="faq-kitchen"><img src="assets/grove-baker.png" alt="Grove answering questions from the home kitchen"><span class="faq-question">How can I help?</span><span class="faq-star">✦</span></div><span class="host-caption">GROVE’S LITTLE HELP CORNER</span></div>`;
d.querySelector('.final-invitation>img').outerHTML=`<div class="closing-world"><img src="assets/grove-owner.png" alt="Grove planning the next chapter at a maker’s desk"><span class="closing-spark">✦</span><span class="closing-note">BIG DREAMS.<br>LITTLE BEGINNINGS.</span></div>`;
return t.innerHTML};
authPage=function(){const t=document.createElement('template');t.innerHTML=authV3();t.content.querySelector('.auth-scene>img').outerHTML=welcomeScene();t.content.querySelector('.scene-location').textContent='YOUR OWN LITTLE WELCOME TO GROVE';t.content.querySelector('#real-auth-form').insertAdjacentHTML('afterend','<p class="local-access-note">Preview accounts stay in this browser. Please use a test password.</p>');return t.innerHTML};
let motionPaused=matchMedia('(prefers-reduced-motion: reduce)').matches,toolsPaused=false,motionObserver=null,toolTimer=null;
function advanceTools(){if(toolsPaused||motionPaused||document.hidden)return;const el=$('#tool-preview');if(!el||el.getBoundingClientRect().bottom<0||el.getBoundingClientRect().top>innerHeight||el.closest('.tools-showcase').matches(':hover,:focus-within'))return;const tabs=['customers','calendar','finance','insights'];toolTab=tabs[(tabs.indexOf(toolTab)+1)%tabs.length];el.innerHTML=toolPreview();document.querySelectorAll('[data-brand="tool-tab"]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===toolTab);b.setAttribute('aria-selected',b.dataset.tab===toolTab)})}
const shellBeforeMotion=shell;
shell=function(){clearInterval(toolTimer);motionObserver?.disconnect();shellBeforeMotion();document.body.classList.toggle('motion-paused',motionPaused);if(route==='landing'){toolTimer=setInterval(advanceTools,4500);motionObserver=new IntersectionObserver(entries=>entries.forEach(e=>{e.target.classList.toggle('in-view',e.isIntersecting)}),{threshold:.08});document.querySelectorAll('.landing-section,.motion-scene,.final-invitation').forEach(el=>motionObserver.observe(el));}if(authStatus==='signed-in'&&!['landing','login','signup'].includes(route)){const target=document.querySelector('#content');target?.insertAdjacentHTML('beforeend','<button class="signout-local" data-motion="signout">Log out</button>')}};
window.addEventListener('click',e=>{const b=e.target.closest('[data-motion]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();if(b.dataset.motion==='pause'){motionPaused=!motionPaused;document.body.classList.toggle('motion-paused',motionPaused);b.textContent=motionPaused?'Play animation ▷':'Pause animation Ⅱ';b.setAttribute('aria-pressed',motionPaused)}if(b.dataset.motion==='tools'){toolsPaused=!toolsPaused;b.textContent=toolsPaused?'Play showcase ▷':'Pause showcase Ⅱ';b.setAttribute('aria-pressed',toolsPaused)}if(b.dataset.motion==='signout'){persist();sessionStorage.removeItem('grove-local-session');authStatus='signed-out';authUser=null;state=structuredClone(localDefaults);location.hash='/login'}},true);
const accountsKey='grove-local-accounts-v1',localDefaults=structuredClone(state);
function localAccounts(){try{return JSON.parse(localStorage.getItem(accountsKey)||'{}')}catch{return {}}}
const persistBeforeAccounts=persist;
persist=function(){if(authUser){const accounts=localAccounts();if(accounts[authUser.email]){accounts[authUser.email].state=state;try{localStorage.setItem(accountsKey,JSON.stringify(accounts))}catch{toast('Your browser could not save these changes.')}return}}persistBeforeAccounts()};
try{const email=sessionStorage.getItem('grove-local-session'),account=localAccounts()[email];if(account){authUser={email,name:account.name};authStatus='signed-in';state=account.state||structuredClone(localDefaults)}}catch{}
async function passwordDigest(password,salt){const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:Uint8Array.from(salt),iterations:100000,hash:'SHA-256'},material,256);return Array.from(new Uint8Array(bits),x=>x.toString(16).padStart(2,'0')).join('')}
document.addEventListener('submit',async e=>{if(e.target.id!=='real-auth-form')return;e.preventDefault();e.stopImmediatePropagation();if(authBusy)return;const form=e.target,fd=new FormData(form),email=String(fd.get('email')).trim().toLowerCase(),password=String(fd.get('password')),signup=form.dataset.kind==='signup',error=$('#auth-error'),submit=form.querySelector('[type="submit"]');authBusy=true;submit.disabled=true;submit.textContent='Opening your Grove…';error.hidden=true;try{const accounts=localAccounts();let account=accounts[email];if(signup){const name=String(fd.get('account-name')||'').trim(),chosen=fd.getAll('interests');if(!name)throw Error('Please enter your name.');if(!chosen.length)throw Error('Choose at least one interest to personalise your discoveries.');if(password.length<8)throw Error('Please use at least 8 characters.');if(account)throw Error('This email already has an account in this browser. Please log in.');const salt=Array.from(crypto.getRandomValues(new Uint8Array(16)));const fresh=structuredClone(localDefaults);fresh.profile={...fresh.profile,name,email,phone:'',interests:chosen};fresh.saved=[];fresh.chain=[];fresh.visits=[];fresh.isBusiness=false;account={name,salt,hash:await passwordDigest(password,salt),state:fresh};accounts[email]=account;localStorage.setItem(accountsKey,JSON.stringify(accounts));}else{if(!account)throw Error('No account with this email in this browser yet. Sign up to get started.');if(await passwordDigest(password,account.salt)!==account.hash)throw Error('That password doesn’t match. Please try again.')}sessionStorage.setItem('grove-local-session',email);authUser={email,name:account.name};authStatus='signed-in';state=account.state;category=entryIntent.category;region='All';savedOnly=false;location.hash=entryIntent.route||'/customer/home';toast(signup?'Your Grove is ready. Welcome!':'Welcome back!');}catch(err){error.textContent=err.message||'Unable to save your account. Check browser storage is enabled.';error.hidden=false;}finally{authBusy=false;submit.disabled=false;submit.textContent=signup?'Create account':'Log in'}},true);

handleRoute();
