/* Motion, visual discovery, and browser-local preview accounts. */
logo=(light=false)=>`<a class="grove-logo grove-wordmark v4-logo ${light?'light':''}" href="#/landing" aria-label="The Grove homepage"><img src="assets/grove-symbol.svg" alt=""><span><small>the</small><b>grove</b></span></a>`;
imgs.cookies='https://images.unsplash.com/photo-1652284303404-4f46665cbb6f?auto=format&fit=crop&w=1000&q=85';
imgs.beauty='https://images.unsplash.com/photo-1728842920167-8122270260fe?auto=format&fit=crop&w=1000&q=85';
imgs.jewellery='https://images.unsplash.com/photo-1585832641917-c40a6d4cec77?auto=format&fit=crop&w=1000&q=85';
businesses.find(b=>b.id===4).image='cookies';
imgs.clay='https://images.unsplash.com/photo-1595351298020-038700609878?auto=format&fit=crop&w=1000&q=85';
imgs.fern='https://unsplash.com/photos/r0M9HrfJMBM/download?force=true&w=1000';
businesses.find(b=>b.id===5).image='clay';
businesses.find(b=>b.id===6).image='fern';
const motionScene=(extra='')=>`<div class="motion-scene ${extra}" role="img" aria-label="Grove waves and blinks in a neighbourhood of home businesses"></div>`;
const welcomeScene=()=>`<div class="welcome-world"><span class="welcome-orbit orbit-one">✦</span><span class="welcome-orbit orbit-two">♡</span><div class="welcome-ticket">YOUR NEXT CHAPTER<span>starts with a hello.</span></div><img class="welcome-mascot" src="assets/grove-mascot.png" alt="Grove bouncing and greeting you"><span class="welcome-floor"></span><span class="welcome-pill">A LITTLE CURIOUS. VERY YOU.</span></div>`;
const landingBeforeMotion=landing;
landing=function(){const t=document.createElement('template');t.innerHTML=landingBeforeMotion();const d=t.content;
d.querySelector('.landing').classList.add('v4-landing');
d.querySelector('.hero-ctas [data-entry="owner"]')?.remove();
d.querySelector('.hero-text>p').textContent='Singapore’s little businesses. Your next big favourite. Discover makers near you and get $1 off each next stop in your chain.';
d.querySelector('#hero-scene-image').outerHTML=motionScene('hero-motion');
d.querySelector('.scene-selector').outerHTML='<button class="motion-control" data-motion="pause" aria-pressed="false">Pause animation Ⅱ</button>';
d.querySelectorAll('.process-section,.why-section,.owner-section,.recommendation-note').forEach(x=>x.remove());
d.querySelector('.v3-about').innerHTML=`<div><span class="eyebrow">SMALL BUSINESSES. STRONGER CONNECTIONS.</span><h2>Local feels<br><em>more personal.</em></h2><p>Our mission: help Singapore’s home-grown talent get discovered, and give every little business room to grow.</p></div><div class="mission-art"><span class="mission-loop"></span><div class="mission-node node-a">♡<strong>Find your people</strong><small>Curious locals</small></div><div class="mission-node node-b">✦<strong>Share your passion</strong><small>Home-grown makers</small></div><span class="mission-label">A neighbourhood of possibility</span></div>`;
d.querySelector('.benefit-strip').remove();
const photos=[imgs.bread,imgs.beauty,imgs.pottery,imgs.jewellery];
d.querySelectorAll('.category-tile').forEach((el,i)=>{el.querySelector('.category-doodle').remove();el.insertAdjacentHTML('afterbegin',`<div class="category-photo"><img src="${photos[i]}" alt="${['Fresh artisan bread','Bottled skincare','Handcrafted ceramics','Gold jewellery'][i]}" loading="lazy"><span>${['Taste something good','Make time for yourself','Made with imagination','Wear a little personality'][i]}</span></div>`);el.querySelector('p').remove()});
d.querySelectorAll('.chain-business-symbol').forEach((el,i)=>el.innerHTML=`<img src="${[imgs.bread,imgs.pottery,imgs.jewellery][i]}" alt="" loading="lazy">`);
d.querySelector('.chain-explainer').textContent='First stop starts your chain. Each next different business: $1 off. Four stops = $3 saved.';
d.querySelector('.tools-showcase').id='owners';
d.querySelector('.tools-showcase>div:first-child').insertAdjacentHTML('beforeend',`<div class="studio-actions">${entryButton('Grow your business','owner','btn')}<button class="motion-control" data-motion="tools" aria-pressed="false">Pause showcase Ⅱ</button></div>`);
d.querySelector('#tool-preview').setAttribute('role','tabpanel');
d.querySelectorAll('.faq-section details').forEach((el,i)=>{if(i===1||i===5)el.remove()});
d.querySelector('.faq-grove').outerHTML=`<div class="faq-host"><div class="faq-kitchen"><img src="assets/grove-baker.png" alt="Grove answering questions from the home kitchen"><span class="faq-question">How can I help?</span><span class="faq-star">✦</span></div><span class="host-caption">GROVE’S LITTLE HELP CORNER</span></div>`;
d.querySelector('.final-invitation>img').outerHTML=`<div class="closing-world"><img src="assets/grove-owner.png" alt="Grove planning the next chapter at a maker’s desk"><span class="closing-spark">✦</span><span class="closing-note">BIG DREAMS.<br>LITTLE BEGINNINGS.</span></div>`;
return t.innerHTML};
authPage=function(){const t=document.createElement('template');t.innerHTML=authV3();t.content.querySelector('.auth-scene>img').outerHTML=welcomeScene();t.content.querySelector('.scene-location').textContent='YOUR OWN LITTLE WELCOME TO GROVE';t.content.querySelector('#real-auth-form').insertAdjacentHTML('afterend','<p class="local-access-note">Preview accounts stay in this browser. Please use a test password.</p>');return t.innerHTML};
let motionPaused=matchMedia('(prefers-reduced-motion: reduce)').matches,toolsPaused=false,motionObserver=null,toolTimer=null;
function advanceTools(){if(toolsPaused||motionPaused||document.hidden)return;const el=$('#tool-preview');if(!el||el.getBoundingClientRect().bottom<0||el.getBoundingClientRect().top>innerHeight||el.closest('.tools-showcase').matches(':focus-within'))return;const tabs=['customers','calendar','finance','insights'];toolTab=tabs[(tabs.indexOf(toolTab)+1)%tabs.length];el.innerHTML=toolPreview();document.querySelectorAll('[data-brand="tool-tab"]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===toolTab);b.setAttribute('aria-selected',b.dataset.tab===toolTab)})}
const shellBeforeMotion=shell;
shell=function(){clearInterval(toolTimer);motionObserver?.disconnect();shellBeforeMotion();document.body.classList.toggle('motion-paused',motionPaused);if(route==='landing'){toolTimer=setInterval(advanceTools,1000);motionObserver=new IntersectionObserver(entries=>entries.forEach(e=>{e.target.classList.toggle('in-view',e.isIntersecting)}),{threshold:.08});document.querySelectorAll('.landing-section,.motion-scene,.final-invitation').forEach(el=>motionObserver.observe(el));}if(authStatus==='signed-in'&&!['landing','login','signup'].includes(route)){const target=document.querySelector('#content');target?.insertAdjacentHTML('beforeend','<button class="signout-local" data-motion="signout">Log out</button>')}};
window.addEventListener('click',e=>{const b=e.target.closest('[data-motion]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();if(b.dataset.motion==='pause'){motionPaused=!motionPaused;document.body.classList.toggle('motion-paused',motionPaused);b.textContent=motionPaused?'Play animation ▷':'Pause animation Ⅱ';b.setAttribute('aria-pressed',motionPaused)}if(b.dataset.motion==='tools'){toolsPaused=!toolsPaused;b.textContent=toolsPaused?'Play showcase ▷':'Pause showcase Ⅱ';b.setAttribute('aria-pressed',toolsPaused)}if(b.dataset.motion==='signout'){persist();sessionStorage.removeItem('grove-local-session');authStatus='signed-out';authUser=null;state=structuredClone(localDefaults);location.hash='/login'}},true);
const accountsKey='grove-local-accounts-v1',localDefaults=structuredClone(state);
function localAccounts(){try{return JSON.parse(localStorage.getItem(accountsKey)||'{}')}catch{return {}}}
const persistBeforeAccounts=persist;
persist=function(){if(authUser){const accounts=localAccounts();if(accounts[authUser.email]){accounts[authUser.email].state=state;try{localStorage.setItem(accountsKey,JSON.stringify(accounts))}catch{toast('Your browser could not save these changes.')}return}}persistBeforeAccounts()};
try{const email=sessionStorage.getItem('grove-local-session'),account=localAccounts()[email];if(account){authUser={email,name:account.name};authStatus='signed-in';state=account.state||structuredClone(localDefaults)}}catch{}
async function passwordDigest(password,salt){const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:Uint8Array.from(salt),iterations:100000,hash:'SHA-256'},material,256);return Array.from(new Uint8Array(bits),x=>x.toString(16).padStart(2,'0')).join('')}
document.addEventListener('submit',async e=>{if(e.target.id!=='real-auth-form')return;e.preventDefault();e.stopImmediatePropagation();if(authBusy)return;const form=e.target,fd=new FormData(form),email=String(fd.get('email')).trim().toLowerCase(),password=String(fd.get('password')),signup=form.dataset.kind==='signup',error=$('#auth-error'),submit=form.querySelector('[type="submit"]');authBusy=true;submit.disabled=true;submit.textContent='Opening your Grove…';error.hidden=true;try{const accounts=localAccounts();let account=accounts[email];if(signup){const name=String(fd.get('account-name')||'').trim(),chosen=fd.getAll('interests');if(!name)throw Error('Please enter your name.');if(!chosen.length)throw Error('Choose at least one interest to personalise your discoveries.');if(password.length<8)throw Error('Please use at least 8 characters.');if(account)throw Error('This email already has an account in this browser. Please log in.');const salt=Array.from(crypto.getRandomValues(new Uint8Array(16)));const fresh=structuredClone(localDefaults);fresh.profile={...fresh.profile,name,email,phone:'',interests:chosen};fresh.saved=[];fresh.chain=[];fresh.visits=[];fresh.isBusiness=false;account={name,salt,hash:await passwordDigest(password,salt),state:fresh};accounts[email]=account;localStorage.setItem(accountsKey,JSON.stringify(accounts));}else{if(!account)throw Error('No account with this email in this browser yet. Sign up to get started.');if(await passwordDigest(password,account.salt)!==account.hash)throw Error('That password doesn’t match. Please try again.')}sessionStorage.setItem('grove-local-session',email);authUser={email,name:account.name};authStatus='signed-in';state=account.state;category=entryIntent.category;region='All';savedOnly=false;location.hash=entryIntent.route||'/customer/home';toast(signup?'Your Grove is ready. Welcome!':'Welcome back!');}catch(err){error.textContent=err.message||'Unable to save your account. Check browser storage is enabled.';error.hidden=false;}finally{authBusy=false;submit.disabled=false;submit.textContent=signup?'Create account':'Log in'}},true);


/* Refined landing experience — keeps the restored Grove visual identity. */
let curiosityIndex=0;
const curiosityPhotos=[imgs.bread,imgs.beauty,imgs.pottery,imgs.jewellery];
function curiosityView(){const i=curiosityIndex,c=interests[i],matches=businesses.filter(b=>b.category===c).slice(0,2);return `<div class="curiosity-photo"><img src="${curiosityPhotos[i]}" alt="${esc(c)}"><span class="curiosity-photo-label">${['SOMETHING DELICIOUS','A MOMENT FOR YOU','MADE WITH IMAGINATION','YOUR OWN KIND OF STYLE'][i]}</span></div><div class="curiosity-story"><span class="eyebrow">0${i+1} / FOLLOW THAT FEELING</span><h3>${['A little bite.<br>A lovely discovery.','Make a little<br>room for yourself.','For the joy<br>of making.','Find the pieces<br>that feel like you.'][i]}</h3><p>${['Meet the home bakers turning everyday ingredients into someone’s new favourite.','Explore a world of thoughtful self-care and little everyday rituals.','From a first pottery lesson to a handmade keepsake. Follow your creative side.','Thoughtful accessories and personal touches. Let your next favourite find you.'][i]}</p>${matches.length?`<div class="curiosity-makers">${matches.map(b=>`<a href="#/login" data-entry="customer" data-entry-store="${b.id}" data-entry-category="${c}"><span>${esc(b.area)}</span><strong>${esc(b.name)} ↗</strong><small>${esc(b.tag)}</small></a>`).join('')}</div>`:'<p class="curiosity-new">Choose this interest when you sign up to personalise your discoveries.</p>'}${entryButton('Explore '+c.toLowerCase(),'customer','btn secondary',c)}<small class="curiosity-footnote">Illustrative businesses and photography</small></div>`}
const refinedLandingBase=landing;
landing=function(){const t=document.createElement('template');t.innerHTML=refinedLandingBase();const d=t.content;d.querySelector('.landing').classList.add('refined-landing');d.querySelector('.hero-motion').outerHTML=`<div class="seamless-neighbourhood" role="img" aria-label="Grove waves in a gently moving neighbourhood scene">${[0,1,2,3].map(i=>`<span class="scene-frame frame-${i}"></span>`).join('')}</div>`;
d.querySelector('.mission-art').outerHTML=`<div class="mission-cinema"><div class="mission-picture"><img src="assets/grove-owner.png" alt="Grove helping a maker plan their next chapter"></div><span class="mission-caption caption-top">A LITTLE PASSION</span><span class="mission-caption caption-bottom">A WHOLE COMMUNITY</span><span class="mission-cinema-note">Your next favourite.<br>Someone’s next big chapter.</span></div>`;
d.querySelector('.visual-chain').innerHTML=`<div class="connection-path">${[['01','Your first spark','Find something you love.','Your first visit'],['02','A new connection','Meet a different local maker.','$1 off'],['03','Keep exploring','There’s more around the corner.','Another $1 off']].map(([n,h,p,r])=>`<article class="connection-stop"><span class="connection-number">${n}</span><h3>${h}</h3><p>${p}</p><span class="reward-ticket">${r}</span></article>`).join('')}</div>`;
d.querySelector('.public-showcase').remove();d.querySelector('.category-section').innerHTML=`<div class="section-title"><div><span class="eyebrow">FOLLOW YOUR CURIOSITY. FIND YOUR NEXT FAVOURITE.</span><h2>What’s your<br><em>kind of lovely?</em></h2></div><p>Pick a passion.<br>Meet the people behind it.</p></div><div class="curiosity-tabs" role="tablist" aria-label="Explore your interests">${interests.map((c,i)=>`<button role="tab" id="curiosity-tab-${i}" aria-controls="curiosity-panel" aria-selected="${i===curiosityIndex}" class="${i===curiosityIndex?'active':''}" data-curiosity="${i}"><span>${catIcons[i]}</span>${c}</button>`).join('')}</div><div id="curiosity-panel" role="tabpanel" aria-labelledby="curiosity-tab-${curiosityIndex}" class="curiosity-panel">${curiosityView()}</div>`;
d.querySelector('.faq-section>div:last-child').innerHTML=[['FOR CUSTOMERS','How do I find my next favourite?','Choose an interest or explore a Singapore region in Discover. Open a business profile to see its story, offerings and booking options.'],['FOR CUSTOMERS','How do chain rewards work?','Your first visit starts a chain. Each next different participating business gives $1 off, up to $3 across four stops.'],['FOR CUSTOMERS','Can I save businesses for later?','Tap a heart on a business to save it. Find it again in Saved or on your profile.'],['FOR BUSINESS OWNERS','How do I register my business?','Start with a customer account. In Settings, choose Sign up as business to create your profile and open your business studio.'],['FOR BUSINESS OWNERS','What can I manage in my studio?','Keep your storefront, customer records, orders, appointments and finances together, with insights to help you plan your next step.'],['FOR BUSINESS OWNERS','Can I preview my storefront?','Yes. Use Preview storefront in your business studio to see how your business appears to customers.']].map(([tag,q,a])=>`<details><summary><small>${tag}</small>${q}<span>+</span></summary><p>${a}</p></details>`).join('');return t.innerHTML};
const refinedAuthBase=authPage;
authPage=function(){entryIntent={...entryIntent,role:'customer',route:entryIntent.route.startsWith('/owner/')?'/customer/settings':entryIntent.route};return refinedAuthBase().replace('YOUR NEXT CHAPTER','YOUR LITTLE BEGINNING').replace('starts with a hello.','Hello, you.').replace('Sign in to explore local businesses and build your chain.',route==='signup'?'Create your customer account and find your favourites.':'Sign in to your customer account.')};
const refinedEntryBase=beginEntry;
beginEntry=function(role='customer',cat='All',storeId=null){if(role==='owner'){entryIntent={role:'customer',category:'All',route:'/customer/settings'};sessionStorage.setItem('grove-entry-intent',JSON.stringify(entryIntent));location.hash=authStatus==='signed-in'?'/customer/settings':'/login';return}refinedEntryBase('customer',cat,storeId)};
const refinedTourBase=tourView;
tourView=function(){refinedTourBase();const modal=$('#modal');modal.classList.add('refined-tour');const n=tourStops.length,chosen=tourStops[n-1]?.id||'explore',scene=chosen==='bakes'?'grove-baker.png':n===3||['craft','accessories'].includes(chosen)?'grove-owner.png':'grove-neighbourhood.png';const host=modal.querySelector('.tour-host');host.innerHTML=`<div class="tour-film film-${chosen}"><img class="tour-film-backdrop" src="assets/${scene}" alt="${chosen==='bakes'?'Grove in a home bakery':n===3?'Grove planning the next discovery':'Grove exploring the neighbourhood'}"><span class="film-shade"></span><div class="film-caption"><small>${n===3?'YOUR LITTLE JOURNEY':n?'YOUR NEXT CHAPTER':'LET CURIOSITY LEAD'}</small><strong>${n===3?'Good things grow together.':({bakes:'Something lovely is baking.',craft:'A little time to create.',wellness:'A moment just for you.',accessories:'Find your own kind of lovely.',explore:'Where shall we begin?'})[chosen]}</strong><span>${n===3?'Three stops. Two connections. $2 saved.':n?'Choose another kind of good below.':'Pick a passion. Let Grove show you around.'}</span></div></div>`;};
window.addEventListener('click',e=>{const b=e.target.closest('[data-curiosity]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();curiosityIndex=Number(b.dataset.curiosity);const panel=$('#curiosity-panel');panel.innerHTML=curiosityView();panel.setAttribute('aria-labelledby','curiosity-tab-'+curiosityIndex);document.querySelectorAll('[data-curiosity]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-selected',x===b)})},true);
handleRoute();
