/* Grove experience: Singapore discovery, shared assistance and open motion scenes. */
const extraStores=[
['North','Woodlands','Knead & Neighbour',0,'Weekend buns','Buns to brighten your morning',14],['North','Yishun','Dew Ritual',1,'Facial care consultation','A softer moment in your week',32],['North','Sembawang','Thread Stories',3,'Hand-sewn pouch','Everyday pieces with personality',24],['North','Yishun','Paper Moon Atelier',2,'Paper craft workshop','Make a little magic with paper',38],
['South','Telok Blangah','Soft Hour Studio',1,'Nail art appointment','A little colour, a little confidence',35],['South','Tiong Bahru','Loop & Lovely',3,'Beaded bracelet','Small details, big personality',22],['South','Bukit Merah','Kopi at Home',0,'Coffee tasting set','Your next slow-morning ritual',16],['South','Outram','Ink & Kind',2,'Watercolour session','A splash of curiosity',45],
['East','Pasir Ris','Glow Kindly',1,'Skin consultation','Thoughtful care for your everyday',30],['East','Tampines','Ribbon Theory',3,'Handmade hair ribbon','Tie a little joy into your day',18],['East','Bedok','Stitch Sunday',2,'Embroidery workshop','Find your rhythm, one stitch at a time',40],['East','Simei','Little Mochi Club',0,'Mochi tasting box','Little bites worth sharing',20],
['West','Jurong East','Calm Canvas',1,'Wellness consultation','Make room for a quieter moment',38],['West','Clementi','Pebble & Pearl',3,'Freshwater pearl bracelet','A personal finishing touch',36],['West','Bukit Batok','Honey Hearth',0,'Honey cake','Baked with care, shared with love',25],['West','Choa Chu Kang','Woven Weekend',2,'Weaving workshop','Something beautiful, made by you',42],
['Central','Bishan','Flour & Friends',0,'Pastry selection','Your neighbourhood sweet spot',18],['Central','Toa Payoh','Kind Skin',1,'Personal care consultation','Care that fits your routine',30],['Central','Ang Mo Kio','Little Loom',2,'Textile workshop','Find your creative thread',40],['Central','Serangoon','Everyday Muse',3,'Handmade tote','Made for your everyday adventures',32]
];
const regionGeo={North:[1.435,103.80],South:[1.285,103.82],East:[1.35,103.94],West:[1.355,103.73],Central:[1.355,103.85]};
const storePhotos=['1509440159596-0249088772ff', '1556229010-6c3f2c9ca5f8', '1553062407-98eeb64c6a62', '1455390582262-044cdead277a', '1604654894610-df63bc536371', '1611652022419-a9419f74343d', '1447933601403-0c6688de566e', '1513364776144-60967b0f800f', '1570172619644-dfd03ed5d881', '1529139513065-c5a7b1fbb4a4', '1452860606245-08befc0ff44b', '1488477181946-6428a0291777', '1540555700478-4be289fbecef', '1535632066927-ab7c9ab60908', '1578985545062-69928b1d9587', '1494438639946-1ebd1d20bf85', '1555507036-ab1f4038808a', '1556228720-195a672e8a03', '1604881988758-f76ad2f7aac1', '1544816155-12df9643f363'];
extraStores.forEach((row,i)=>{const [r,area,name,c,product,tag,price]=row,id=i+7,key='brand-'+id;imgs[key]='https://images.unsplash.com/photo-'+storePhotos[i]+'?auto=format&fit=crop&w=900&q=85';businesses.push({id,name,category:interests[c],area,region:r,distance:4+i*.6,rating:'New',reviews:0,price,image:key,tag,description:tag+'. Explore a home-grown '+interests[c].toLowerCase()+' business in '+area+'.',owner:name+' team',x:30+i,y:35,menu:[[product,price],[product+' · gift set',price+12]]});coordinates[id]=[regionGeo[r][0]+(i%3)*.006,regionGeo[r][1]+(i%4)*.005]});
imgs['brand-16']='https://images.unsplash.com/photo-1488893441583-0054a3aca255?auto=format&fit=crop&w=900&q=85';
imgs['brand-17']='https://images.unsplash.com/photo-1657668282135-b620193e7801?auto=format&fit=crop&w=900&q=85';
imgs['brand-22']='https://unsplash.com/photos/_KCrSolz6FI/download?force=true&w=900';
imgs['brand-25']='https://unsplash.com/photos/6-HTjxp21xo/download?force=true&w=900';
customerNav.push(['assistant','leaf','Ask Grove']);
const freeGrove=(cls='')=>`<div class="free-grove ${cls}" aria-label="Grove gently sways and floats"><span class="grove-halo"></span><span class="orbit-word word-one">discover</span><img src="assets/grove-mascot.png" alt="Grove, your friendly neighbourhood guide"><span class="orbit-word word-two">connect</span><span class="orbit-word word-three">grow</span></div>`;
const homeBeforeV5=home;home=function(){let html=homeBeforeV5();const t=document.createElement('template');t.innerHTML=html;const cards=t.content.querySelector('.cards');let list=filtered();if(savedOnly&&!list.length){cards.innerHTML=`<div class="saved-intro"><h2>Your next favourite is waiting.</h2><p>You haven’t saved a business yet. Try these suggestions and tap a heart to make this list yours.</p></div>`+businesses.slice(6,10).map(card).join('')}else cards.innerHTML=list.map(card).join('');cards.insertAdjacentHTML('afterend','<p class=directory-note>Illustrative business profiles · representative photography</p>');return t.innerHTML};
const mapRegions={West:[[95,355],[150,230],[275,195],[350,270],[330,375],[205,415]],North:[[275,195],[320,125],[460,105],[560,170],[525,260],[350,270]],Central:[[350,270],[525,260],[570,340],[475,405],[330,375]],East:[[560,170],[680,225],[770,280],[825,355],[735,410],[570,340],[525,260]],South:[[205,415],[330,375],[475,405],[570,340],[735,410],[620,450],[490,485],[345,470]]};
const mapCentres={West:[240,300],North:[425,190],Central:[450,325],East:[690,325],South:[470,440]},mapPoints={};
businesses.forEach(b=>{const c=mapCentres[b.region],index=businesses.filter(x=>x.region===b.region).findIndex(x=>x.id===b.id),offset=[[-48,-35],[0,-45],[48,-35],[-48,35],[0,45],[48,35]][index%6];mapPoints[b.id]=[600-c[1]-offset[1],c[0]+offset[0]]});
function discoveryListV5(){const list=filtered();return savedOnly&&!state.saved.length?businesses.filter(b=>(region==='All'||b.region===region)&&(category==='All'||b.category===category)&&(!query||(b.name+' '+b.area+' '+b.category).toLowerCase().includes(query.toLowerCase()))).slice(0,4):list}
discover=function(){const list=discoveryListV5();return heading('A little island. A lot to discover.','Choose a region, follow your curiosity, meet a local maker.')+searchBox()+chips()+`<div class="region-pills">${['All','North','South','East','West','Central'].map(r=>`<button data-v5="region" data-region="${r}" class="chip ${region===r?'active':''}" aria-pressed="${region===r}">${r==='All'?'All Singapore':r+' Singapore'}</button>`).join('')}<button class="chip" data-new="locate">Use my location</button></div>${geoMessage?`<p class="muted" role="status">${esc(geoMessage)}</p>`:''}<div class="island-layout"><section class="island-map-wrap"><div class="map-title"><span>SINGAPORE · YOUR LOCAL WORLD</span><button class="text-btn" data-v5="reset-map">Reset view ↺</button></div><div id="leaflet-map" aria-label="Illustrated Singapore regions. Drag to pan, use plus and minus to zoom, or select a region." tabindex="0"></div><p class="island-note">Illustrative directory · approximate store positions · Singapore only</p></section><section class="island-results"><h2>${list.length} ${savedOnly&&!state.saved.length?'favourites to discover':savedOnly?'saved favourites':'little discoveries'}</h2><p>${region==='All'?'Across Singapore':region+' Singapore'} · ${category==='All'?'All interests':esc(category)}</p>${savedOnly&&!state.saved.length?'<p>No favourites saved yet. These are suggestions—tap a store and save it with the heart button.</p>':''}<div id="map-results">${mapResults(list)}</div>${savedOnly&&!list.length?'<p>Save a business with its heart button to see it here.</p><button class="btn secondary" data-v5="show-all">Find a favourite</button>':''}</section></div>`};
initMap=function(){if(!$('#leaflet-map')||!window.L)return;leafMap=L.map('leaflet-map',{crs:L.CRS.Simple,zoomAnimation:false,markerZoomAnimation:false,fadeAnimation:false,minZoom:-1,maxZoom:1.5,zoomSnap:.25,scrollWheelZoom:false,maxBounds:[[-80,-80],[680,980]],maxBoundsViscosity:1,attributionControl:false}).fitBounds([[60,60],[520,860]]);const colors={West:'#b6cbbb',North:'#dce5b9',Central:'#f3d7a5',East:'#c2dcd1',South:'#e9bda6'};Object.entries(mapRegions).forEach(([name,pts])=>{const poly=L.polygon(pts.map(([x,y])=>[600-y,x]),{color:'#fcfbf4',weight:5,fillColor:colors[name],fillOpacity:(region==='All'||region===name)?0.95:0.3,className:'island-region'}).addTo(leafMap);poly.on('click',()=>{region=name;renderPage()});const [x,y]=mapCentres[name];L.marker([600-y,x],{interactive:false,icon:L.divIcon({className:'region-name',html:name.toUpperCase(),iconSize:[100,25],iconAnchor:[50,12]})}).addTo(leafMap)});discoveryListV5().forEach(b=>L.marker(mapPoints[b.id],{title:b.name,alt:b.name,icon:L.divIcon({className:'island-store-pin',html:`<span style="--pin-delay:${b.id%5*.3}s">${b.id}</span>`,iconSize:[32,40],iconAnchor:[16,35]})}).addTo(leafMap).bindPopup(`<div class="map-popup"><small>${esc(b.category)}</small><strong>${esc(b.name)}</strong><p>${esc(b.area)}</p><button class="btn small" data-new="open-store" data-id="${b.id}">Step inside</button></div>`));if(region!=='All'){const [x,y]=mapCentres[region];leafMap.setView([600-y,x],.25)}leafMap.invalidateSize()};
const settingsBeforeV5=settings;settings=function(){const t=document.createElement('template');t.innerHTML=settingsBeforeV5();t.content.querySelector('#motion-setting')?.closest('label').remove();t.content.querySelector('[data-setting="reminders"]')?.closest('label').remove();return t.innerHTML};
const profileBeforeV5=profile;profile=function(){return '<div class="profile-experience">'+profileBeforeV5().replace('Your demo bookings','Your appointments')+`<a class="profile-discover-link" href="#/customer/discover"><span>YOUR NEXT CHAPTER</span><strong>There’s more of Singapore to love. ↗</strong></a></div>`};
history=function(){return heading('Your local story, so far.','The people you’ve met. The little things you’ve loved.')+`<div class="history-banner"><span class="eyebrow">EVERY VISIT LEAVES A LITTLE GOOD</span><strong>${new Set(state.visits.map(v=>v.business)).size}<em> local connections</em></strong><div><span>${state.visits.length} visits</span><span>${money(cashSaved())} saved</span><span>${state.saved.length} favourites</span></div></div><div class="visit-timeline">${state.visits.length?state.visits.map((v,i)=>{const b=business(v.business);return `<article class="visit-memory"><span class="memory-date">${date(v.date)}</span><img src="${imgs[b.image]}" alt="${esc(b.name)}"><div><span class="eyebrow">${b.area} · ${b.category}</span><h2>${esc(b.name)}</h2><p>${money(v.amount)} spent · ${v.discount?money(v.discount)+' saved':'The start of something good'}</p><button class="text-btn" data-new="open-store" data-id="${b.id}">Rediscover this favourite ↗</button></div></article>`}).join(''):`<div class="history-empty">${freeGrove('history-guide')}<div><h2>A fresh page.<br>A whole island of possibilities.</h2><p>Your visits will build a personal trail of local favourites here.</p><a class="btn" href="#/customer/discover">Find your first stop</a></div></div>`}</div>`};
const dashBeforeV5=dashboard;dashboard=function(){const t=document.createElement('template');t.innerHTML=dashBeforeV5();const totalsNow=totals(financeMonth);t.content.querySelector('.stats').innerHTML=stat('Orders recorded',state.orders.length,'Your order book')+stat('Awaiting payment',money(totalsNow.pending),'Outstanding balances')+stat('Paid income',money(totalsNow.income),financeMonth)+stat('Net profit',money(totalsNow.profit),'Income less expenses');return t.innerHTML};
const insightsBeforeV5=insights;insights=function(){return insightsBeforeV5().replace('Women in sample','Gender · Female').replace('SYNTHETIC DEMO DATA','ILLUSTRATIVE DATA').replace('Voluntarily shared · demo','Self-reported gender').replace('Synthetic sample','Illustrative records')};
const ownerAnswer=answerQuestion;
answerQuestion=function(q){if(mode==='owner'&&!/find.*(store|food|beauty|craft|fashion)|how.*(reward|chain)|join.*business/i.test(q))return ownerAnswer(q);const text=q.toLowerCase();if(/chain|reward|discount|cashback/.test(text))return{text:'Start with one business at full price. Each next different participating business gives $1 off. Four stops save up to $3. Open My chain to see your progress.',source:'Chain rewards'};if(/sav|favour/.test(text))return{text:`You have ${state.saved.length} saved ${state.saved.length===1?'business':'businesses'}. Tap the heart on a store to save it, then open Saved or your Profile to find it again.`,source:'Your favourites'};if(/book|appoint/.test(text))return{text:'Open a business, choose its booking option and select a date and time. Your appointments appear on your profile. Availability and confirmation currently stay in this browser.',source:'Appointments'};if(/business|sell|join/.test(text)&&/own|join|start|sell|sign/.test(text))return{text:'Start with your customer account. Open Settings → Sign up as business, then complete your business details to open your studio.',source:'Business registration'};if(/near|find|store|food|beauty|craft|fashion|north|south|east|west|central|recommend/.test(text)){const cat=interests.find(c=>text.includes(c.split(' ')[0].toLowerCase()));const reg=Object.keys(regionGeo).find(r=>text.includes(r.toLowerCase()));const picks=businesses.filter(b=>(!cat||b.category===cat)&&(!reg||b.region===reg)).slice(0,3);return{text:'A few places to explore: '+picks.map(b=>b.name+' in '+b.area).join('; ')+'. Open Discover to browse their profiles and the Singapore region map.',source:'Grove directory'}}return{text:'I can help you find businesses by interest or region, save favourites, understand chain rewards, book a visit, or join as a business owner. What would you like to explore?',source:'Grove help'}};
const assistantBeforeV5=assistantPage;assistantPage=function(){const t=document.createElement('template');t.innerHTML=assistantBeforeV5();if(mode==='customer'){t.content.querySelector('.knowledge-panel').remove();t.content.querySelector('.assistant-layout').classList.add('customer-chat');t.content.querySelector('#chat-messages').innerHTML=(state.customerChats||[]).map(m=>`<div class="chat-message ${m.role}"><span>${m.role==='user'?'YOU':'GROVE'}</span><p>${esc(m.text)}</p>${m.source?`<small>${esc(m.source)}</small>`:''}</div>`).join('')||'<div class="chat-welcome"><h3>Hi, I’m Grove.</h3><p>Let’s find your next little favourite.</p></div>';t.content.querySelector('.suggested-questions').innerHTML=['Find food in North Singapore','How do rewards work?','Where are my favourites?','How do I book?'].map(q=>`<button class="chip" data-new="ask" data-question="${q}">${q}</button>`).join('');}t.content.querySelector('.chat-heading .muted').textContent='Your local guide, one question at a time.';return t.innerHTML.replace('Ask about your business, or teach your demo assistant something new.',mode==='customer'?'Find your next favourite, plan a visit, or get a little help.':'Get help with orders, customers, finances and everyday questions.').replace('No AI service connected. Answers come from local rules and your saved demo data.','Grove uses directory information and saved records. It may not have every answer.')};
const sendBeforeV5=sendChat;sendChat=function(q){if(mode==='owner'){sendBeforeV5(q);return}const text=q.trim();if(!text)return;state.customerChats??=[];state.customerChats.push({role:'user',text},{role:'assistant',...answerQuestion(text)});persist();renderPage()};
window.addEventListener('click',e=>{if(mode==='customer'&&e.target.closest('[data-new="clear-chat"]')){e.preventDefault();e.stopImmediatePropagation();state.customerChats=[];persist();renderPage()}},true);
const renderBeforeV5=renderPage;
function polishCopy(){const root=document.querySelector('#app');if(!root)return;const nodes=[];[root,document.querySelector('#modal'),document.querySelector('#grove-floating')].filter(Boolean).forEach(el=>{const walker=document.createTreeWalker(el,NodeFilter.SHOW_TEXT);while(walker.nextNode())nodes.push(walker.currentNode)});nodes.forEach(n=>{n.textContent=n.textContent.replace(/Demo workspace/g,'Business studio').replace(/In-store demo orders/g,'Orders & sales').replace(/Record a sample sale/g,'Record a sale').replace(/demo bookings/g,'appointments').replace(/demo visit/g,'visit').replace(/Demo visit/g,'Visit').replace(/demo businesses/g,'businesses').replace(/local demo business profile/g,'business profile in this workspace').replace(/your demo assistant/g,'Grove assistant').replace(/Confirm demo visit/g,'Confirm visit').replace(/Demo only\. No purchase is made\./g,'No payment is collected here.').replace(/demo finance records/g,'finance records').replace(/demo appointments/g,'appointments').replace(/Your demo calendar/g,'Your calendar').replace(/Your demo finance records/g,'Your finance records').replace(/\bdemo\s*/gi,'')})}
renderPage=function(){renderBeforeV5();polishCopy()};
const modalBeforeV5=showModal;showModal=function(html){modalBeforeV5(html);polishCopy()};
const shellBeforeV5=shell;shell=function(){shellBeforeV5();polishCopy()};
window.addEventListener('click',e=>{const a=e.target.closest('[data-action="category"]');if(a){savedOnly=false;}const s=e.target.closest('[data-action="saved-filter"]');if(s){category='All';region='All';query=''}const focus=e.target.closest('[data-new="focus-pin"]');if(focus){e.preventDefault();e.stopImmediatePropagation();const id=Number(focus.dataset.id),point=mapPoints[id];leafMap?.setView(point,.75);leafMap?.eachLayer(layer=>{if(layer.getLatLng&&layer.getLatLng().lat===point[0]&&layer.getLatLng().lng===point[1]&&layer.openPopup)layer.openPopup()});return}const el=e.target.closest('[data-v5]');if(!el)return;e.preventDefault();e.stopImmediatePropagation();if(el.dataset.v5==='region'){region=el.dataset.region;renderPage()}if(el.dataset.v5==='reset-map'){region='All';renderPage()}if(el.dataset.v5==='show-all'){savedOnly=false;category='All';region='All';renderPage()}},true);

// A compact region selector keeps the map, rather than its filters, in focus.
const discoverBeforeV9=discover;
discover=function(){const t=document.createElement('template');t.innerHTML=discoverBeforeV9();t.content.querySelector('.region-pills').innerHTML=`<label class="region-select">Explore <select id="grove-region" aria-label="Singapore region">${['All','North','South','East','West','Central'].map(r=>`<option value="${r}" ${region===r?'selected':''}>${r==='All'?'All Singapore':r}</option>`).join('')}</select></label><button class="chip nearby-button" data-new="locate" title="Use my location to find nearby businesses">⌖ Nearby</button><span class="map-instruction">Drag to explore · tap a marker</span>`;return t.innerHTML};
window.addEventListener('change',e=>{if(e.target.id==='grove-region'){region=e.target.value;renderPage()}},true);
const historyBeforeV9=history;
history=function(){const t=document.createElement('template');t.innerHTML=historyBeforeV9();const guide=t.content.querySelector('.history-guide');if(guide)guide.outerHTML=`<div class="grove-explorer" aria-label="Grove the curious explorer, ready for a new adventure"><span class="explorer-orbit"></span><span class="explorer-spark spark-a">✦</span><span class="explorer-spark spark-b">✧</span><span class="explorer-stamp">GROVE’S FIELD NOTES<br><b>01 / THE BEGINNING</b></span><img src="assets/grove-mascot.png" alt="Grove the neighbourhood explorer with a trusty orange satchel"><span class="explorer-passport">LOCAL<br><strong>EXPLORER</strong><small>Collect moments, not miles.</small></span><span class="explorer-trail">⌁ · · · ✦</span></div>`;return t.innerHTML};
let groveChatOpen=false,groveChatMode='';
function paintGroveChat(){document.querySelector('#grove-floating')?.remove();document.querySelectorAll('.nav a[href$="/assistant"]').forEach(a=>a.remove());if(!['customer','owner'].includes(mode)||['landing','login','signup'].includes(route))return;if(groveChatMode!==mode){groveChatOpen=false;groveChatMode=mode}const host=document.createElement('div');host.id='grove-floating';host.innerHTML=`${groveChatOpen?`<section id="grove-chat-drawer" class="grove-chat-drawer" role="dialog" aria-label="Chat with Grove"><header class="floating-chat-header"><div><strong>Grove, at your service.</strong><small>${mode==='owner'?'A little help for your business':'Your friendly neighbourhood guide'}</small></div><button data-grove-chat="close" aria-label="Close Grove chat">×</button></header><div class="floating-chat-body">${assistantPage()}</div></section>`:''}<button class="grove-chat-launcher" data-grove-chat="toggle" aria-label="${groveChatOpen?'Close Grove chat':'Chat with Grove'}" aria-expanded="${groveChatOpen}" aria-controls="grove-chat-drawer"><img src="assets/grove-mascot.png" alt=""><span>${groveChatOpen?'×':'•••'}</span></button>`;document.body.append(host);polishCopy();if(groveChatOpen){const messages=host.querySelector('#chat-messages');if(messages)messages.scrollTop=messages.scrollHeight}}
const renderBeforeV9=renderPage;renderPage=function(){leafMap?.stop();renderBeforeV9();paintGroveChat()};
const shellBeforeV9=shell;shell=function(){shellBeforeV9();paintGroveChat()};
sendChat=function(q){const text=q.trim();if(!text)return;const key=mode==='owner'?'chats':'customerChats';state[key]??=[];state[key].push({role:'user',text},{role:'assistant',...answerQuestion(text)});persist();if(groveChatOpen){paintGroveChat();document.querySelector('#grove-floating #chat-query')?.focus()}else renderPage()};
window.addEventListener('click',e=>{const el=e.target.closest('[data-grove-chat]');if(!el)return;e.preventDefault();e.stopImmediatePropagation();groveChatOpen=el.dataset.groveChat==='close'?false:!groveChatOpen;paintGroveChat();if(groveChatOpen)document.querySelector('#grove-floating #chat-query')?.focus();else document.querySelector('.grove-chat-launcher')?.focus()},true);
window.addEventListener('keydown',e=>{if(e.key==='Escape'&&groveChatOpen){groveChatOpen=false;paintGroveChat();document.querySelector('.grove-chat-launcher')?.focus()}});
handleRoute();
